import type { CollectibleIcon, CollectibleKind } from "../domain/collectibles";
import type { BadgeIcon } from "./badgeIcons";
import {
  AnchorIcon,
  ArkIcon,
  BookIcon,
  CandleIcon,
  CityIcon,
  CompassIcon,
  CrossIcon,
  CrownIcon,
  DoveIcon,
  FishIcon,
  FlameIcon,
  HarpIcon,
  HeartIcon,
  LadderIcon,
  LampIcon,
  MoonIcon,
  OliveIcon,
  PathIcon,
  PeakIcon,
  PersonIcon,
  PinIcon,
  QuillIcon,
  ScrollIcon,
  ShieldIcon,
  SlingIcon,
  SparkIcon,
  SproutIcon,
  StaffIcon,
  StarIcon,
  SunIcon,
  SunriseIcon,
  TabletsIcon,
  TentIcon,
  TombIcon,
  WaveIcon,
  WellIcon,
} from "./icons";

/** Ícono de cada ficha y de cada etapa de la línea temporal (el contenido elige por nombre). */
export const COLLECTIBLE_ICON: Record<CollectibleIcon, BadgeIcon> = {
  anchor: AnchorIcon,
  ark: ArkIcon,
  book: BookIcon,
  candle: CandleIcon,
  city: CityIcon,
  compass: CompassIcon,
  cross: CrossIcon,
  crown: CrownIcon,
  dove: DoveIcon,
  fish: FishIcon,
  flame: FlameIcon,
  harp: HarpIcon,
  heart: HeartIcon,
  ladder: LadderIcon,
  lamp: LampIcon,
  moon: MoonIcon,
  olive: OliveIcon,
  path: PathIcon,
  peak: PeakIcon,
  quill: QuillIcon,
  scroll: ScrollIcon,
  shield: ShieldIcon,
  sling: SlingIcon,
  spark: SparkIcon,
  sprout: SproutIcon,
  staff: StaffIcon,
  star: StarIcon,
  sun: SunIcon,
  sunrise: SunriseIcon,
  tablets: TabletsIcon,
  tent: TentIcon,
  tomb: TombIcon,
  wave: WaveIcon,
  well: WellIcon,
};

/** Ícono de cada tipo de ficha (pestañas y avisos). */
export const KIND_ICON: Record<CollectibleKind, BadgeIcon> = {
  character: PersonIcon,
  place: PinIcon,
  event: ScrollIcon,
};
